-- FIRE Tracker Schema

-- FIRE configuration (single row per user)
create table fire_config (
  id uuid primary key default gen_random_uuid(),
  user_email text not null unique,
  annual_expenses_target numeric(12,2) not null,  -- desired annual spend in retirement
  swr numeric(5,4) not null default 0.035,         -- safe withdrawal rate (pessimistic default: 3.5%)
  expected_return numeric(5,4) not null default 0.05, -- real return after inflation (pessimistic: 5%)
  inflation_rate numeric(5,4) not null default 0.04,  -- assumed inflation (pessimistic: 4%)
  current_age integer not null,
  target_retirement_age integer,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Monthly net worth snapshots (from IBKR + bank uploads)
create table net_worth_snapshots (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  snapshot_month date not null,   -- first day of the month this covers
  investment_value numeric(14,2) not null default 0,
  cash_value numeric(14,2) not null default 0,
  other_assets numeric(14,2) not null default 0,
  total_liabilities numeric(14,2) not null default 0,
  notes text,
  source_upload_ids uuid[],        -- which uploads generated this
  created_at timestamptz default now(),
  unique(user_email, snapshot_month)
);

-- Monthly spending summaries
create table spending_months (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  month date not null,             -- first day of month
  total_spend numeric(12,2) not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_email, month)
);

-- Individual transactions
create table transactions (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  month date not null,
  date date not null,
  description text not null,
  amount numeric(12,2) not null,   -- positive = expense, negative = income/refund
  category text not null default 'Uncategorised',
  is_income boolean not null default false,
  source_upload_id uuid,
  created_at timestamptz default now()
);

-- File uploads (bank statements, IBKR screenshots)
create table uploads (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  upload_type text not null check (upload_type in ('ibkr_screenshot','bank_statement','other')),
  file_name text not null,
  storage_path text not null,
  content_hash text not null,      -- sha256 for dedup
  period_month date,               -- which month this covers
  parse_status text not null default 'pending' check (parse_status in ('pending','processing','done','failed')),
  parse_result jsonb,
  parse_error text,
  created_at timestamptz default now()
);

-- Monthly FIRE analysis reports (generated by AI)
create table fire_reports (
  id uuid primary key default gen_random_uuid(),
  user_email text not null,
  report_month date not null,
  fi_number numeric(14,2),
  current_net_worth numeric(14,2),
  percent_to_fi numeric(7,4),
  years_to_fi_pessimistic numeric(7,2),
  years_to_fi_base numeric(7,2),
  monthly_savings_rate numeric(7,4),
  narrative text,                  -- the critical AI assessment
  spending_critique text,          -- spending-specific critique
  created_at timestamptz default now(),
  unique(user_email, report_month)
);

-- Deduplication constraint on transactions
create unique index on transactions(user_email, date, description, amount, is_income);

-- Indexes
create index on transactions(user_email, month);
create index on net_worth_snapshots(user_email, snapshot_month);
create index on uploads(user_email, content_hash);
create index on uploads(user_email, period_month);
